# Generated by Django 3.0.3 on 2020-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='milk',
            fields=[
                ('产品', models.CharField(max_length=20)),
                ('供货价_含运费', models.FloatField()),
                ('零售价_含运费', models.FloatField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
